### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by carlca** [hSATAC/wifi-password-qr#1]
Go v1.11.4
macOS 10.14.2

Hello, I've just installed using `go get github.com/hSATAC/wifi-password-qr` and then ran `wifi-password-qr`. This is what I got...

```
wifi-password-qr
panic: runtime error: index out of range

goroutine 1 [running]:
main.getWifiInfoFromRegex(0x0, 0x0, 0x412c852, 0xf, 0x0, 0x0)
	/Users/carlca/Code/go/src/github.com/hSATAC/wifi-password-qr/main.go:73 +0x85
main.getWifiInfo(0x41f5488, 0x41f5488, 0x41f5480, 0x41f5480)
	/Users/carlca/Code/go/src/github.com/hSATAC/wifi-password-qr/main.go:57 +0xe3
main.main()
	/Users/carlca/Code/go/src/github.com/hSATAC/wifi-password-qr/main.go:17 +0x34
```

**Comment by hSATAC** [comment]
Hi, thanks for submitting the issue.

I'll add some error handling around the getWifiInfo part.

Could you run `$ /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I`
And paste the  output here?

Thank you. ❤️

**Comment by carlca** [comment]
I got...
```
airport: invalid option -- ~
Unable to retrieve AirPort interface list
Unable to retrieve AirPort interface list
```
I think the problem may be that my WiFi comes via a USB Dongle rather than via Airport devices. I had this issue when trying to use another WiFi related app a few months ago, in which case it's not your problem at all!
